### ISSUE TITLE
doconce jupyterbook: need for running in folder with do.txt file

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#123]
Previously, I could run `doconce jupyterbook src/file.do.txt`. Now that gives a file not found error :

```
path/to/doconce.py", line 4263, in write_file
    f = open(out_filename, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '../../$DEST/01_file.md'
```

A fix is to do

```
cd src
doconce jupyterbook file.do.txt
```

Is this intended behaviour or the unintended result of a recent change?

**Comment by aless80** [comment]
I can successfully run files in other directories such as `doconce jupyterbook test/testdoc.do.txt --examples_as_exercises` . How did you install doconce?

I thought this was solved in issue #114 . In commit [0bf7ad](https://github.com/doconce/doconce/commit/0bf7ad1093484384ee46b3be328e0694277a7d26) `lib/doconce/jupyterbook.py` does:
```
dirname, basename, ext, filename = find_file_with_extensions(sys.argv[1], allowed_extensions=['.do.txt'])
....
if dirname:
        os.chdir(dirname)
```

**Comment by lexnederbragt** [comment]
I install doconce through a `.yaml` file that has this content and I follow the instructions in it:

```
# latest doconce, with scipy
# conda env create -f doconce_doconce_latest.yml
# or, to start from scratch,
# conda env create -f doconce_doconce_latest.yml --force
# install doconce via
# conda activate doconce_doconce_latest
# cd /Users/alexajo/github/doconce_doconce/
# git pull
# python setup.py install
# also add publish via
# pip install publish-doconce

name: doconce_doconce_latest
channels:
  - defaults
dependencies:
  - notebook
  - pip
  - python=3.6
  - pandas
  - matplotlib
  - scipy
```

I did a fresh install ('start from scratch') and the problem persists.

I can confirm being able to run `doconce jupyterbook` on `test/testdoc.do.txt`.

However, some more digging showed this - all in this executed in the root of the doconce repo folder:

**1) `test/testdoc.do.txt`**

```
mkdir book
doconce jupyterbook test/testdoc.do.txt --examples_as_exercises --dest=book --no_abort
```

Runs fine

```
doconce jupyterbook test/testdoc.do.txt --examples_as_exercises --dest=$PWD/book --no_abort
```

Gives the error

```
mkdir /Users/alexajo/Downloads/book
doconce jupyterbook test/testdoc.do.txt --examples_as_exercises --dest=/Users/alexajo/Downloads/book --no_abort
```

Gives the error.

**2) testdoc.do.txt**

```
cd test
mkdir book
```

Now all commands run fine:

```
doconce jupyterbook testdoc.do.txt --examples_as_exercises --dest=book --no_abort
doconce jupyterbook testdoc.do.txt --examples_as_exercises --dest=$PWD/book --no_abort
doconce jupyterbook testdoc.do.txt --examples_as_exercises --dest=/Users/alexajo/Downloads/book --no_abort
```

It seems to be a problem associated with paths in the `--dest` option when the command is run in a different folder than the `do.txt` file.

**Comment by aless80** [comment]
Moved to #124
